# Generated by Django 4.0.5 on 2022-06-12 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
